metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: images
  anno_path: annotations/train.json
  dataset_dir: /dataset
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: images
  anno_path: annotations/train.json
  dataset_dir: /dataset
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/train.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /dataset # if set, anno_path will be 'dataset_dir/anno_path'
